export type SeoLanguage = 'es' | 'en';

export type SeoRouteKey = 'home' | 'about' | 'programs' | 'stories' | 'story' | 'donate' | 'contact';

export type SeoChangeFrequency = 'always' | 'hourly' | 'daily' | 'weekly' | 'monthly' | 'yearly' | 'never';

export interface SeoRouteMetadata {
  path: `/${string}`;
  title: string;
  description: string;
  priority: number;
  changeFrequency: SeoChangeFrequency;
  isStoryDetailPage: boolean;
  language: SeoLanguage;
  routeKey: SeoRouteKey;
  canonicalPath: `/${string}`;
  alternatePaths: Record<SeoLanguage, `/${string}`>;
  storyId?: string;
  isLegacySpanishAlias?: boolean;
}

const homeDescription = {
  es: 'Fundación Costa Palmas impulsa educación, salud, conservación ambiental y bienestar comunitario en Cabo del Este, Baja California Sur.',
  en: 'Fundación Costa Palmas advances education, health, environmental conservation, and community well-being in Cabo del Este, Baja California Sur.',
};

const staticRouteMetadata = [
  {
    path: '/',
    title: 'Fundación Costa Palmas | Comunidad y Conservación',
    description: homeDescription.es,
    priority: 0.8,
    changeFrequency: 'weekly',
    isStoryDetailPage: false,
    language: 'es',
    routeKey: 'home',
    canonicalPath: '/es',
    alternatePaths: { es: '/es', en: '/en' },
    isLegacySpanishAlias: true,
  },
  {
    path: '/es',
    title: 'Fundación Costa Palmas | Comunidad y Conservación',
    description: homeDescription.es,
    priority: 1,
    changeFrequency: 'weekly',
    isStoryDetailPage: false,
    language: 'es',
    routeKey: 'home',
    canonicalPath: '/es',
    alternatePaths: { es: '/es', en: '/en' },
  },
  {
    path: '/en',
    title: 'Fundación Costa Palmas | Community and Conservation',
    description: homeDescription.en,
    priority: 1,
    changeFrequency: 'weekly',
    isStoryDetailPage: false,
    language: 'en',
    routeKey: 'home',
    canonicalPath: '/en',
    alternatePaths: { es: '/es', en: '/en' },
  },
  {
    path: '/nosotros',
    title: 'Nosotros | Fundación Costa Palmas',
    description: 'Conoce la historia, el equipo, los valores y los aliados que impulsan el trabajo de Fundación Costa Palmas en Cabo del Este.',
    priority: 0.5,
    changeFrequency: 'yearly',
    isStoryDetailPage: false,
    language: 'es',
    routeKey: 'about',
    canonicalPath: '/es/nosotros',
    alternatePaths: { es: '/es/nosotros', en: '/en/about' },
    isLegacySpanishAlias: true,
  },
  {
    path: '/es/nosotros',
    title: 'Nosotros | Fundación Costa Palmas',
    description: 'Conoce la historia, el equipo, los valores y los aliados que impulsan el trabajo de Fundación Costa Palmas en Cabo del Este.',
    priority: 0.7,
    changeFrequency: 'yearly',
    isStoryDetailPage: false,
    language: 'es',
    routeKey: 'about',
    canonicalPath: '/es/nosotros',
    alternatePaths: { es: '/es/nosotros', en: '/en/about' },
  },
  {
    path: '/en/about',
    title: 'About Us | Fundación Costa Palmas',
    description: 'Learn about the story, team, values, and partners behind Fundación Costa Palmas work in Cabo del Este.',
    priority: 0.7,
    changeFrequency: 'yearly',
    isStoryDetailPage: false,
    language: 'en',
    routeKey: 'about',
    canonicalPath: '/en/about',
    alternatePaths: { es: '/es/nosotros', en: '/en/about' },
  },
  {
    path: '/programas',
    title: 'Programas | Fundación Costa Palmas',
    description: 'Programas de educación, medio ambiente, salud integral y espacios comunitarios que fortalecen a Cabo del Este.',
    priority: 0.6,
    changeFrequency: 'monthly',
    isStoryDetailPage: false,
    language: 'es',
    routeKey: 'programs',
    canonicalPath: '/es/programas',
    alternatePaths: { es: '/es/programas', en: '/en/programs' },
    isLegacySpanishAlias: true,
  },
  {
    path: '/es/programas',
    title: 'Programas | Fundación Costa Palmas',
    description: 'Programas de educación, medio ambiente, salud integral y espacios comunitarios que fortalecen a Cabo del Este.',
    priority: 0.8,
    changeFrequency: 'monthly',
    isStoryDetailPage: false,
    language: 'es',
    routeKey: 'programs',
    canonicalPath: '/es/programas',
    alternatePaths: { es: '/es/programas', en: '/en/programs' },
  },
  {
    path: '/en/programs',
    title: 'Programs | Fundación Costa Palmas',
    description: 'Education, environment, comprehensive health, and community space programs strengthening Cabo del Este.',
    priority: 0.8,
    changeFrequency: 'monthly',
    isStoryDetailPage: false,
    language: 'en',
    routeKey: 'programs',
    canonicalPath: '/en/programs',
    alternatePaths: { es: '/es/programas', en: '/en/programs' },
  },
  {
    path: '/historias',
    title: 'Historias de Impacto | Fundación Costa Palmas',
    description: 'Historias reales de impacto comunitario, educación, salud y conservación ambiental en Cabo del Este.',
    priority: 0.6,
    changeFrequency: 'monthly',
    isStoryDetailPage: false,
    language: 'es',
    routeKey: 'stories',
    canonicalPath: '/es/historias',
    alternatePaths: { es: '/es/historias', en: '/en/stories' },
    isLegacySpanishAlias: true,
  },
  {
    path: '/es/historias',
    title: 'Historias de Impacto | Fundación Costa Palmas',
    description: 'Historias reales de impacto comunitario, educación, salud y conservación ambiental en Cabo del Este.',
    priority: 0.8,
    changeFrequency: 'monthly',
    isStoryDetailPage: false,
    language: 'es',
    routeKey: 'stories',
    canonicalPath: '/es/historias',
    alternatePaths: { es: '/es/historias', en: '/en/stories' },
  },
  {
    path: '/en/stories',
    title: 'Impact Stories | Fundación Costa Palmas',
    description: 'Real stories of community impact, education, health, and environmental conservation in Cabo del Este.',
    priority: 0.8,
    changeFrequency: 'monthly',
    isStoryDetailPage: false,
    language: 'en',
    routeKey: 'stories',
    canonicalPath: '/en/stories',
    alternatePaths: { es: '/es/historias', en: '/en/stories' },
  },
  {
    path: '/donar',
    title: 'Donar | Fundación Costa Palmas',
    description: 'Apoya los programas de Fundación Costa Palmas y contribuye al bienestar de las comunidades de Cabo del Este.',
    priority: 0.55,
    changeFrequency: 'monthly',
    isStoryDetailPage: false,
    language: 'es',
    routeKey: 'donate',
    canonicalPath: '/es/donar',
    alternatePaths: { es: '/es/donar', en: '/en/donate' },
    isLegacySpanishAlias: true,
  },
  {
    path: '/es/donar',
    title: 'Donar | Fundación Costa Palmas',
    description: 'Apoya los programas de Fundación Costa Palmas y contribuye al bienestar de las comunidades de Cabo del Este.',
    priority: 0.75,
    changeFrequency: 'monthly',
    isStoryDetailPage: false,
    language: 'es',
    routeKey: 'donate',
    canonicalPath: '/es/donar',
    alternatePaths: { es: '/es/donar', en: '/en/donate' },
  },
  {
    path: '/en/donate',
    title: 'Donate | Fundación Costa Palmas',
    description: 'Support Fundación Costa Palmas programs and contribute to the well-being of Cabo del Este communities.',
    priority: 0.75,
    changeFrequency: 'monthly',
    isStoryDetailPage: false,
    language: 'en',
    routeKey: 'donate',
    canonicalPath: '/en/donate',
    alternatePaths: { es: '/es/donar', en: '/en/donate' },
  },
  {
    path: '/contacto',
    title: 'Contacto | Fundación Costa Palmas',
    description: 'Contacta a Fundación Costa Palmas para colaborar, donar, ser voluntario o conocer más sobre sus programas.',
    priority: 0.5,
    changeFrequency: 'yearly',
    isStoryDetailPage: false,
    language: 'es',
    routeKey: 'contact',
    canonicalPath: '/es/contacto',
    alternatePaths: { es: '/es/contacto', en: '/en/contact' },
    isLegacySpanishAlias: true,
  },
  {
    path: '/es/contacto',
    title: 'Contacto | Fundación Costa Palmas',
    description: 'Contacta a Fundación Costa Palmas para colaborar, donar, ser voluntario o conocer más sobre sus programas.',
    priority: 0.7,
    changeFrequency: 'yearly',
    isStoryDetailPage: false,
    language: 'es',
    routeKey: 'contact',
    canonicalPath: '/es/contacto',
    alternatePaths: { es: '/es/contacto', en: '/en/contact' },
  },
  {
    path: '/en/contact',
    title: 'Contact | Fundación Costa Palmas',
    description: 'Contact Fundación Costa Palmas to collaborate, donate, volunteer, or learn more about its programs.',
    priority: 0.7,
    changeFrequency: 'yearly',
    isStoryDetailPage: false,
    language: 'en',
    routeKey: 'contact',
    canonicalPath: '/en/contact',
    alternatePaths: { es: '/es/contacto', en: '/en/contact' },
  },
] satisfies SeoRouteMetadata[];

const storyRouteMetadata = [
  {
    path: '/historias/proteccion-palmar',
    title: 'Un compromiso con la protección del Palmar | Fundación Costa Palmas',
    description: 'La protección de nuestros ecosistemas es una de las prioridades fundamentales de Fundación Costa Palmas. El Palmar de Cabo del Este es un pulmón vital.',
    priority: 0.45,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'es',
    routeKey: 'story',
    storyId: 'proteccion-palmar',
    canonicalPath: '/es/historias/proteccion-palmar',
    alternatePaths: { es: '/es/historias/proteccion-palmar', en: '/en/stories/protecting-palmar' },
    isLegacySpanishAlias: true,
  },
  {
    path: '/es/historias/proteccion-palmar',
    title: 'Un compromiso con la protección del Palmar | Fundación Costa Palmas',
    description: 'La protección de nuestros ecosistemas es una de las prioridades fundamentales de Fundación Costa Palmas. El Palmar de Cabo del Este es un pulmón vital.',
    priority: 0.6,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'es',
    routeKey: 'story',
    storyId: 'proteccion-palmar',
    canonicalPath: '/es/historias/proteccion-palmar',
    alternatePaths: { es: '/es/historias/proteccion-palmar', en: '/en/stories/protecting-palmar' },
  },
  {
    path: '/en/stories/protecting-palmar',
    title: 'A commitment to protecting the Palmar | Fundación Costa Palmas',
    description: 'Protecting our ecosystems is one of Fundacion Costa Palmas core priorities. The Palmar of Cabo del Este is a vital lung for our region.',
    priority: 0.6,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'en',
    routeKey: 'story',
    storyId: 'proteccion-palmar',
    canonicalPath: '/en/stories/protecting-palmar',
    alternatePaths: { es: '/es/historias/proteccion-palmar', en: '/en/stories/protecting-palmar' },
  },
  {
    path: '/historias/diagnostico-corazon',
    title: 'Un diagnóstico a tiempo puede cambiarlo todo | Fundación Costa Palmas',
    description: 'Para muchas familias en Cabo del Este, una consulta con un especialista no siempre está al alcance. Y cuando se trata del corazón, el tiempo es clave.',
    priority: 0.45,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'es',
    routeKey: 'story',
    storyId: 'diagnostico-corazon',
    canonicalPath: '/es/historias/diagnostico-corazon',
    alternatePaths: { es: '/es/historias/diagnostico-corazon', en: '/en/stories/timely-heart-diagnosis' },
    isLegacySpanishAlias: true,
  },
  {
    path: '/es/historias/diagnostico-corazon',
    title: 'Un diagnóstico a tiempo puede cambiarlo todo | Fundación Costa Palmas',
    description: 'Para muchas familias en Cabo del Este, una consulta con un especialista no siempre está al alcance. Y cuando se trata del corazón, el tiempo es clave.',
    priority: 0.6,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'es',
    routeKey: 'story',
    storyId: 'diagnostico-corazon',
    canonicalPath: '/es/historias/diagnostico-corazon',
    alternatePaths: { es: '/es/historias/diagnostico-corazon', en: '/en/stories/timely-heart-diagnosis' },
  },
  {
    path: '/en/stories/timely-heart-diagnosis',
    title: 'A timely diagnosis can change everything | Fundación Costa Palmas',
    description: 'For many families in Cabo del Este, seeing a specialist is not always within reach. And when it comes to the heart, timing is essential.',
    priority: 0.6,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'en',
    routeKey: 'story',
    storyId: 'diagnostico-corazon',
    canonicalPath: '/en/stories/timely-heart-diagnosis',
    alternatePaths: { es: '/es/historias/diagnostico-corazon', en: '/en/stories/timely-heart-diagnosis' },
  },
  {
    path: '/historias/becas-uabcs',
    title: 'Invertir en educación es invertir en el futuro de la comunidad | Fundación Costa Palmas',
    description: 'En Cabo del Este, acceder a la educación superior es un paso importante, pero no siempre es fácil mantenerse en ella.',
    priority: 0.45,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'es',
    routeKey: 'story',
    storyId: 'becas-uabcs',
    canonicalPath: '/es/historias/becas-uabcs',
    alternatePaths: { es: '/es/historias/becas-uabcs', en: '/en/stories/uabcs-scholarships' },
    isLegacySpanishAlias: true,
  },
  {
    path: '/es/historias/becas-uabcs',
    title: 'Invertir en educación es invertir en el futuro de la comunidad | Fundación Costa Palmas',
    description: 'En Cabo del Este, acceder a la educación superior es un paso importante, pero no siempre es fácil mantenerse en ella.',
    priority: 0.6,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'es',
    routeKey: 'story',
    storyId: 'becas-uabcs',
    canonicalPath: '/es/historias/becas-uabcs',
    alternatePaths: { es: '/es/historias/becas-uabcs', en: '/en/stories/uabcs-scholarships' },
  },
  {
    path: '/en/stories/uabcs-scholarships',
    title: "Investing in education is investing in the community's future | Fundación Costa Palmas",
    description: 'In Cabo del Este, accessing higher education is an important step, but staying in school is not always easy.',
    priority: 0.6,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'en',
    routeKey: 'story',
    storyId: 'becas-uabcs',
    canonicalPath: '/en/stories/uabcs-scholarships',
    alternatePaths: { es: '/es/historias/becas-uabcs', en: '/en/stories/uabcs-scholarships' },
  },
  {
    path: '/historias/campana-vacunacion',
    title: 'Exitosa campaña de vacunación para 100 mascotas | Fundación Costa Palmas',
    description: 'La salud pública también incluye el bienestar de nuestros animales de compañía. La jornada de vacunación benefició a más de 100 mascotas.',
    priority: 0.45,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'es',
    routeKey: 'story',
    storyId: 'campana-vacunacion',
    canonicalPath: '/es/historias/campana-vacunacion',
    alternatePaths: { es: '/es/historias/campana-vacunacion', en: '/en/stories/vaccination-campaign' },
    isLegacySpanishAlias: true,
  },
  {
    path: '/es/historias/campana-vacunacion',
    title: 'Exitosa campaña de vacunación para 100 mascotas | Fundación Costa Palmas',
    description: 'La salud pública también incluye el bienestar de nuestros animales de compañía. La jornada de vacunación benefició a más de 100 mascotas.',
    priority: 0.6,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'es',
    routeKey: 'story',
    storyId: 'campana-vacunacion',
    canonicalPath: '/es/historias/campana-vacunacion',
    alternatePaths: { es: '/es/historias/campana-vacunacion', en: '/en/stories/vaccination-campaign' },
  },
  {
    path: '/en/stories/vaccination-campaign',
    title: 'Successful vaccination campaign for 100 companion animals | Fundación Costa Palmas',
    description: 'Public health also includes the well-being of our companion animals. The vaccination and deworming campaign benefited more than 100 animals.',
    priority: 0.6,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'en',
    routeKey: 'story',
    storyId: 'campana-vacunacion',
    canonicalPath: '/en/stories/vaccination-campaign',
    alternatePaths: { es: '/es/historias/campana-vacunacion', en: '/en/stories/vaccination-campaign' },
  },
  {
    path: '/historias/rehabilitacion-esperanza',
    title: 'Cuando la rehabilitación está más cerca, también lo está la esperanza | Fundación Costa Palmas',
    description: 'La alianza con CRIT acerca servicios especializados de rehabilitación e inclusión a niñas, niños y familias de Baja California Sur.',
    priority: 0.45,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'es',
    routeKey: 'story',
    storyId: 'rehabilitacion-esperanza',
    canonicalPath: '/es/historias/rehabilitacion-esperanza',
    alternatePaths: { es: '/es/historias/rehabilitacion-esperanza', en: '/en/stories/rehabilitation-brings-hope-closer' },
    isLegacySpanishAlias: true,
  },
  {
    path: '/es/historias/rehabilitacion-esperanza',
    title: 'Cuando la rehabilitación está más cerca, también lo está la esperanza | Fundación Costa Palmas',
    description: 'La alianza con CRIT acerca servicios especializados de rehabilitación e inclusión a niñas, niños y familias de Baja California Sur.',
    priority: 0.6,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'es',
    routeKey: 'story',
    storyId: 'rehabilitacion-esperanza',
    canonicalPath: '/es/historias/rehabilitacion-esperanza',
    alternatePaths: { es: '/es/historias/rehabilitacion-esperanza', en: '/en/stories/rehabilitation-brings-hope-closer' },
  },
  {
    path: '/en/stories/rehabilitation-brings-hope-closer',
    title: 'When rehabilitation is closer, so is hope | Fundación Costa Palmas',
    description: 'The partnership with CRIT brings specialized rehabilitation and inclusion services closer to children and families in Baja California Sur.',
    priority: 0.6,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'en',
    routeKey: 'story',
    storyId: 'rehabilitacion-esperanza',
    canonicalPath: '/en/stories/rehabilitation-brings-hope-closer',
    alternatePaths: { es: '/es/historias/rehabilitacion-esperanza', en: '/en/stories/rehabilitation-brings-hope-closer' },
  },
  {
    path: '/historias/deporte-comunidad',
    title: 'Donde vuelve el deporte, vuelve la comunidad | Fundación Costa Palmas',
    description: 'La rehabilitación del Estadio Estrellas de Miraflores devolvió a la comunidad un espacio para el deporte, la convivencia y el desarrollo.',
    priority: 0.45,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'es',
    routeKey: 'story',
    storyId: 'deporte-comunidad',
    canonicalPath: '/es/historias/deporte-comunidad',
    alternatePaths: { es: '/es/historias/deporte-comunidad', en: '/en/stories/sports-bring-community-back' },
    isLegacySpanishAlias: true,
  },
  {
    path: '/es/historias/deporte-comunidad',
    title: 'Donde vuelve el deporte, vuelve la comunidad | Fundación Costa Palmas',
    description: 'La rehabilitación del Estadio Estrellas de Miraflores devolvió a la comunidad un espacio para el deporte, la convivencia y el desarrollo.',
    priority: 0.6,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'es',
    routeKey: 'story',
    storyId: 'deporte-comunidad',
    canonicalPath: '/es/historias/deporte-comunidad',
    alternatePaths: { es: '/es/historias/deporte-comunidad', en: '/en/stories/sports-bring-community-back' },
  },
  {
    path: '/en/stories/sports-bring-community-back',
    title: 'Where sports return, community returns | Fundación Costa Palmas',
    description: 'The rehabilitation of Estadio Estrellas de Miraflores restored a community space for sports, connection, and youth development.',
    priority: 0.6,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'en',
    routeKey: 'story',
    storyId: 'deporte-comunidad',
    canonicalPath: '/en/stories/sports-bring-community-back',
    alternatePaths: { es: '/es/historias/deporte-comunidad', en: '/en/stories/sports-bring-community-back' },
  },
  {
    path: '/historias/playa-se-conserva',
    title: 'Una playa se conserva todos los días, no solo cuando la visitamos | Fundación Costa Palmas',
    description: 'Fundación Costa Palmas y ZOFEMAT Los Cabos renuevan su compromiso con el cuidado de Playa El Surgidero y la certificación Blue Flag.',
    priority: 0.45,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'es',
    routeKey: 'story',
    storyId: 'playa-se-conserva',
    canonicalPath: '/es/historias/playa-se-conserva',
    alternatePaths: { es: '/es/historias/playa-se-conserva', en: '/en/stories/preserving-the-beach-every-day' },
    isLegacySpanishAlias: true,
  },
  {
    path: '/es/historias/playa-se-conserva',
    title: 'Una playa se conserva todos los días, no solo cuando la visitamos | Fundación Costa Palmas',
    description: 'Fundación Costa Palmas y ZOFEMAT Los Cabos renuevan su compromiso con el cuidado de Playa El Surgidero y la certificación Blue Flag.',
    priority: 0.6,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'es',
    routeKey: 'story',
    storyId: 'playa-se-conserva',
    canonicalPath: '/es/historias/playa-se-conserva',
    alternatePaths: { es: '/es/historias/playa-se-conserva', en: '/en/stories/preserving-the-beach-every-day' },
  },
  {
    path: '/en/stories/preserving-the-beach-every-day',
    title: 'A beach is preserved every day, not only when we visit it | Fundación Costa Palmas',
    description: 'Fundación Costa Palmas and ZOFEMAT Los Cabos renew their commitment to caring for Playa El Surgidero and maintaining Blue Flag standards.',
    priority: 0.6,
    changeFrequency: 'monthly',
    isStoryDetailPage: true,
    language: 'en',
    routeKey: 'story',
    storyId: 'playa-se-conserva',
    canonicalPath: '/en/stories/preserving-the-beach-every-day',
    alternatePaths: { es: '/es/historias/playa-se-conserva', en: '/en/stories/preserving-the-beach-every-day' },
  },
] satisfies SeoRouteMetadata[];

export const routeMetadataManifest = [
  ...staticRouteMetadata,
  ...storyRouteMetadata,
] as const satisfies readonly SeoRouteMetadata[];

export const prerenderRoutes = routeMetadataManifest.map((route) => route.path);

export const getRouteMetadata = (path: string) => (
  routeMetadataManifest.find((route) => route.path === path)
);
